### ISSUE TITLE
Stopping. The search results count is missing.

### ISSUE THREAD

**Issue by r0ckinxj3** [urbanadventurer/bing-ip2hosts#3]
https://asciinema.org/a/dvbbCWthykpgkscsdLDNF2PaT

**Comment by urbanadventurer** [comment]
It is working for me on Linux and macOS. Can you tell me what country your IP address is in?

<img width="633" alt="image" src="https://user-images.githubusercontent.com/101783/79756399-9ed7da00-832b-11ea-9907-f820014ef0c4.png">

**Comment by urbanadventurer** [comment]
Thanks for reporting this issue @0xaajalal 👍  Let me know if you have any more problems.

The issue was Bing.com was responding differently to the latest version of wget. To resolve it we now provide a user agent of `wget/1.19.4` instead of `User-Agent: Wget/1.20.3 (linux-gnu)`.

**Comment by qran253** [comment]
and how to change user-agent ?
