### ISSUE TITLE
Stopping. The search results count is missing.

### ISSUE THREAD

**Issue by geekyneard** [urbanadventurer/bing-ip2hosts#4]
m,            -----.--[ bing-ip2hosts v1.0.2 ]-------------------------
  #####              |  Searching    : 185.199.108.153
  ####b              |  Found        : 1
  ####b              |  Scraped pages: 1
  ####b 1mw,         |
  ####b  1#####Nw,   |  Page Title   : ip:185.199.108.153 . - Bing
  ####i   %########[ |  Results      :
  ####n      2#####[ |  Pagination   :
  ####g  ,#########b |  New          : 1 new
  #############M^    |
  ##########"        |
    "%##"            |  CTRL-C to stop

[▎] /search?q=ip%3A185.199.108.153+.&qs=n&first=00&FORM=PERE&setlang=en-us&setmkt=

Stopping. The search results count is missing.

✓ Found 1 results after scraping 1 pages.

even i had updates wget still showing same error.
My envrironment - Ubuntu 16.04 amd64

**Comment by Mousketeer** [comment]
Same here, linux mint version "tara". Wget version 1.19.4. The generated URL works, but the resulting page has probably changed output format. The sb_count stanza does not appear in the format bing-ip2hosts is looking for.

**Comment by urbanadventurer** [comment]
Thanks for the bug report @geekyneard and @Mousketeer
