### ISSUE TITLE
Issue with user-agent?

### ISSUE THREAD

**Issue by mathieu-aubin** [urbanadventurer/bing-ip2hosts#6]
Im not sure but... it seems like user-agent is returning bad results.

using provided wget 1.19 doesnt expand to anything and just dies...

tries setting 1.20 instead and... well, it got further, anyways (sorry i have yet to figure out what this thing does that i cant do some other way, but im interrested anyways!)

[![asciicast](https://asciinema.org/a/QKqUG2EyRCY4D7DlT2PSD4wmu.svg)](https://asciinema.org/a/QKqUG2EyRCY4D7DlT2PSD4wmu)

**Comment by vvect** [comment]
Looks this operator is no longer functioning on Bing search, if you try to use it directly ie `ip:$IP` it'll return with a blank page.

**Comment by urbanadventurer** [comment]
It works normally with wget/1.20. Thanks.

**Comment by urbanadventurer** [comment]
Fixed with 1.0.5. Gave you credit in the README for the bug fix.
